'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ManualGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  C:\WorkSpace\Prog\ManualGenerator\Db\app.db に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property DBPath() As String
            Get
                Return ResourceManager.GetString("DBPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  C:\WorkSpace\Prog\ManualGenerator\WebDoc\System\PHP\php.exe に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PHPExePath() As String
            Get
                Return ResourceManager.GetString("PHPExePath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  C:\WorkSpace\Prog\ManualGenerator\WebDoc\System\Converter.php に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PHPScriptPath() As String
            Get
                Return ResourceManager.GetString("PHPScriptPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  C:\WorkSpace\Prog\ManualGenerator\WebDoc\Docs\ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PublicDocDir() As String
            Get
                Return ResourceManager.GetString("PublicDocDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  _Public に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PublicSuffix() As String
            Get
                Return ResourceManager.GetString("PublicSuffix", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
